version: "3.9"

services:
  web:
    build: .
    container_name: claire_web
    ports:
      - "8003:8003"
    restart: unless-stopped
    volumes:
      - ./db:/app/db   # Mount volume to store SQLite DB

#volumes:
#  claire_data:
